# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Project

pod 'ZXConvenientCode', :path=>'../ZXConvenientCode'

pod 'React', :path => '../react_native/node_modules/react-native/React.podspec', :subspecs => [ 'Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket','RCTLinkingIOS', 'ART']

end
